---
- hosts: lean_local
  remote_user: vagrant
  sudo: yes
  vars:
    database_server: localhost
    gerrit_download_link: "https://gerrit-releases.storage.googleapis.com/gerrit-2.11.4.war"
    gerrit_home: "/opt/gerrit"
    # gerrit_url: "http://121.42.193.129:8080/"
    gerrit_url: "http://localhost:8080/"
    plsql_user: "postgres"
    db_user: "gerrit"
    db_name: "gerritdb"
    db_password: "gerritpass"
    unix_user: "gerrit"
  roles:
    - common
    - postgres
    - gerrit
