---
- name: install postgresql requirements
  yum: name={{item}}
  with_items:
    - python-psycopg2

- name: ensure user does not have unnecessary privilege
  sudo_user: postgres
  postgresql_user: user={{db_user}} password={{db_password}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: ensure database is created
  sudo_user: postgres
  postgresql_db: name={{db_name}} owner={{db_user}}

- name: ensure user has access to database
  sudo_user: postgres
  postgresql_privs: database={{db_name}} privs=ALL role={{db_user}} objs=ALL_IN_SCHEMA

- name: update pg_hba.conf to ensure local connect
  sudo_user: postgres
  lineinfile: dest=/var/lib/pgsql/9.4/data/pg_hba.conf
              state=present
              backrefs=yes
              regexp="^host\s+all\s+all\s+127\.0\.0\.1\/32\s+ident$"
              line="host\tall\tall\t127.0.0.1/32\ttrust"

- name: start postgres and enable at boot
  service: name=postgresql-9.4 state=restarted enabled=yes

