---
- name: install updated PostgreSQL PGDG
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=present

- name: install postgresql94-server
  yum: pkg=postgresql94-server state=latest

- name: initialize postgresql
  shell: /usr/pgsql-9.4/bin/postgresql94-setup initdb

- name: start postgres service
  service: name=postgresql-9.4 state=started